# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aI1g2MLzS_sViJhhY-QdpQ0UVMEbtfAb
"""

# Data Handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Suppress warnings
import warnings
warnings.filterwarnings("ignore")

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Get the uploaded file name dynamically
file_name = list(uploaded.keys())[0]

# Load the dataset into pandas DataFrame
df = pd.read_csv(file_name)

# Verify the data is loaded
print("✅ Dataset Loaded Successfully!")
print(df.head())

# Check data types
print(df.dtypes)

# Identify non-numeric columns
categorical_cols = df.select_dtypes(include=["object"]).columns
print("\n⚠️ Categorical Columns That Need Encoding:", categorical_cols)

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=["object"]).columns

# Apply Label Encoding to categorical columns
label_encoder = LabelEncoder()
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

# Now, fill missing values (since everything is numeric)
df.fillna(df.mean(), inplace=True)

print("\n✅ Categorical Data Encoded Successfully!")

# Convert Acquisition Cost to Numeric (Remove $ signs and commas)
df["Acquisition_Cost"] = df["Acquisition_Cost"].replace(r"[\$,]", "", regex=True).astype(float)

# Convert Date Column to Datetime (if applicable)
if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"], errors='coerce')

# Create Click-to-Buying Ratio (New Feature)
df["Click_to_Buying"] = df["Conversion_Rate"] * df["Clicks"]

# Fill Missing Values
df.fillna(df.mean(), inplace=True)

# Print summary of missing values
print("\n✅ Missing Values After Cleaning:\n", df.isnull().sum())

# ✅ Step 2: Exploratory Data Analysis (EDA)
print("Dataset Information:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

# ✅ Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# ✅ Print column names before referencing "Date"
print("\nColumns in DataFrame:", df.columns)

# ✅ Convert "Date" column if it exists
if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"])
    print("✅ Date column converted successfully!")
else:
    print("⚠ Warning: 'Date' column not found in DataFrame!")

# ✅ Visualizing distributions of numerical features
df.hist(figsize=(12, 8), bins=20, edgecolor="black")
plt.suptitle("Distribution of Numerical Features", fontsize=14, fontweight="bold")
plt.show()

# ✅ Select only numerical columns for correlation analysis
numerical_features = df.select_dtypes(include=[np.number])

# ✅ Correlation Heatmap
plt.figure(figsize=(10, 6))
corr_matrix = numerical_features.corr()
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap of Key Features")
plt.show()

# ✅ Boxplots to detect outliers
plt.figure(figsize=(12, 6))
sns.boxplot(data=df[["ROI", "Conversion_Rate", "Click_to_Buying", "Impressions", "Engagement_Score"]])
plt.title("Boxplot of Key Features (Outlier Detection)")
plt.xticks(rotation=45)
plt.show()

# ✅ Step 3: Data Cleaning & Preprocessing
df["Acquisition_Cost"] = df["Acquisition_Cost"].replace(r"[\$,]", "", regex=True).astype(float)

# ✅ Create "Click_to_Buying" feature
df["Click_to_Buying"] = df["Conversion_Rate"] * df["Clicks"]

# Extract useful date features
if "Date" in df.columns:
    df["Date_year"] = df["Date"].dt.year
    df["Date_month"] = df["Date"].dt.month
    df["Date_day"] = df["Date"].dt.day
    df["Date_weekday"] = df["Date"].dt.weekday  # ✅ FIXED (No Parentheses)

    # Drop original date column
    df.drop(columns=["Date"], inplace=True)

print("✅ Date Features Extracted Successfully!")

# Define Target Variable
target_column = "ROI"  # Change if needed
X = df.drop(columns=[target_column])  # Features
y = df[target_column]  # Target Variable

# Print dataset shape
print("✅ X shape:", X.shape)
print("✅ y shape:", y.shape)

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = X.select_dtypes(include=["object"]).columns

# Apply Label Encoding to categorical columns
label_encoder = LabelEncoder()
for col in categorical_cols:
    X[col] = label_encoder.fit_transform(X[col])

# Print data types after encoding
print("\n✅ Data Types After Encoding:\n", X.dtypes)

from sklearn.model_selection import train_test_split

# Reduce training size to 50% (to prevent kernel crashes)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

# Print dataset shape
print("✅ Train Set Shape:", X_train.shape, y_train.shape)
print("✅ Test Set Shape:", X_test.shape, y_test.shape)

from sklearn.preprocessing import StandardScaler

# Apply Standard Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("✅ Scaling Completed Successfully!")

from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt

# Train a temporary model to evaluate feature importance
temp_model = RandomForestRegressor(n_estimators=10, random_state=42, n_jobs=-1)
temp_model.fit(X_train_scaled, y_train)

# Get feature importance
feature_importance = pd.Series(temp_model.feature_importances_, index=X_train.columns)

# Plot feature importance
plt.figure(figsize=(10, 5))
feature_importance.sort_values(ascending=False).plot(kind="bar", title="Feature Importance")
plt.show()

# Remove low-importance features (importance score < 0.01)
low_importance_features = feature_importance[feature_importance < 0.01].index
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns).drop(columns=low_importance_features)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns).drop(columns=low_importance_features)

print("✅ Low-importance features removed!")

# 🔥 Select Top Features Based on Importance (Modify based on your results)
important_features = ["Clicks", "Impressions", "Engagement_Score", "Click_to_Buying", "Conversion_Rate"]

# ✅ Keep only the important features
X = df[important_features]
y = df["ROI"]  # Target remains the same

# 🔄 Split data into training & test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 🔍 Apply Standard Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 🎯 Train the Random Forest Model
model = RandomForestRegressor(n_estimators=50, max_depth=10, random_state=42)
model.fit(X_train_scaled, y_train)

# Make Predictions
y_pred = model.predict(X_test_scaled)
print("✅ Predictions Completed!")

# 📊 Evaluate Performance
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n✅ Model Evaluation Metrics:")
print(f"📉 MAE: {mae:.2f}")
print(f"📉 RMSE: {rmse:.2f}")
print(f"📈 R² Score: {r2:.2f}")

# Convert scaled NumPy arrays back to DataFrame with original column names
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

# Select only top important features
top_features = feature_importance[feature_importance > 0.02].index
X_train_selected = X_train_scaled[top_features]  # ✅ No more IndexError
X_test_selected = X_test_scaled[top_features]

